# Generated by Django 5.1.2 on 2024-11-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0006_alter_tag_options_tag_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='imame',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
