# Generated by Django 5.1.2 on 2024-11-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0007_tag_imame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='imame',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
