# Generated by Django 5.1.2 on 2024-11-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_alter_tag_imame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='imame',
            new_name='image',
        ),
    ]
