# Generated by Django 5.1.2 on 2024-11-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
