# Generated by Django 5.1.2 on 2024-11-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0019_post_audio_post_video_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
