# Generated by Django 5.1.2 on 2024-11-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
