# Generated by Django 5.1.2 on 2024-11-11 16:44

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0008_alter_chatgroup_group_name_joinrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='joinrequest',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
