# Generated by Django 5.1.2 on 2024-11-11 18:42

import shortuuid.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0011_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='request_name',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
