# Generated by Django 5.1.2 on 2024-11-14 15:15

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0014_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrequest',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
